name: Continuous integration
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build
